config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  root to: 'home#index'

  resources :libraries do
    collection { post :import}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  validates :name, :city, :country, :url, presence: true
  validates :name, uniqueness: true
  require 'csv'

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      library_hash = row.to_hash
      library = Library.where(id: library_hash["id"])

      if library.count == 1
        library.first.update!(library_hash)
      else
        Library.create!(library_hash)
      end
    end
  end
end

app/models/places_api.rb
class PlacesApi < ApplicationRecord
  def self.get_api_info
    # https://maps.googleapis.com/maps/api/place/nearbysearch/output?parameters
    places_api = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=500&type=restaurant&keyword=cruise&key=#{ENV['GOOGLE_PLACES_API_KEY']}"
    request_to_places_api = Net::HTTP.get(URI(places_api))
    JSON.parse request_to_places_api
  end
end


# PlacesApi.get_api_info.new
#
# GooglePlaces::Client.new (API)

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
    @library = Library.all.sample
      
  end

  def import
    Library.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end


  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:country, :city, :name, :not_interested, :url)
    end
end

app/controllers/places_api_controller.rb
class PlacesApiController < ApplicationController
  def index
    @places_info = PlacesApi.get_api.info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/places_api_helper.rb
module PlacesApiHelper
end

app/views/home/index.html.erb
<h6 class='info'>KABOOM allows you to plan a trip curated to your specifications. Begin by clicking the button to begin your first KABOOM adventure.</h6>
<div class="fullscreen">
  <img class="img" src="http://bit.ly/2ht9vrl" />
    <ul class="slides">
      <li>
        <div class="caption center-align">
          <h3></h3>
          <h5 class="light grey-text text-lighten-3"></h5>
        </div>
      </li>
    </ul>
  </div>

<div class='big-boom'>
  <h1 class='big-kaboom'><%= link_to "KABOOM", libraries_path %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaboom</title>
    <%= csrf_meta_tags %>
    <%= yield :head %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav">
      <li class="active"><a href="/libraries">Home</a></li>
    </ul>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/libraries/_form.html.erb
<div class="new-form">
<%= form_for(library) do |f| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :Image_Url.capitalize %>
    <%= f.text_field :pic_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/libraries/edit.html.erb
<div class="edit-form">
<h1>Editing Library</h1>

<%= content_for :head do %>
  <style>
    body{
      background: url('<%= @library.pic_url %>') center center;
      top: 50%;
      left: 50%;
      width: 500px;
      height: 500px;
      margin-top: -250px;
      margin-left: -250px;
    }
  </style>

<% end %>

<%= render 'form', library: @library %>

<%= link_to '| Show', @library %> |
<%= link_to 'Back |', libraries_path %>
</div>

app/views/libraries/index.html.erb
<% if @library.present? %>
<%= content_for :head do %>
  <style>
    body{
      background: url('<%= @library.pic_url %>') center center;
      top: 50%;
      left: 50%;
      width: 500px;
      height: 500px;
      margin-top: -250px;
      margin-left: -250px;
    }
  </style>

<% end %>

<p id="notice"><%= notice %></p>

  <div class="library-info">
    <div class='title'>
      <h3><a class="library_url"><span class="card-title"><%= link_to @library.name, @library.url %></span></a></h3>
          <ul>
              <h5><li><%= @library.city %>,</li></h5>
              <h5><li><%= @library.country %></li></h5>
          </ul>
        </div>

    <br>

    <td><%= link_to '| Show |', @library %></td>
    <td><%= link_to ' Edit |', edit_library_path(@library) %></td>
    <td><%= link_to 'Destroy |', @library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <p> Not interested in this library? Click below. </p>
    <div class="mini-boom">
      <h5><%= link_to '| KABOOM |', libraries_path %></h5>
    </div>
</div>


<% end %>

app/views/libraries/new.html.erb
<div class="new-library-form">


<h5>Add your own library</h5>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

<br>

<div class="import">
<h5>Import a CSV File</h5>
  <%= form_tag import_libraries_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>
</div>

app/views/libraries/show.html.erb
  <%= content_for :head do %>
    <style>
      body{
        background: url('<%= @library.pic_url %>') center center;
        top: 50%;
        left: 50%;
        width: 500px;
        height: 500px;
        margin-top: -250px;
        margin-left: -250px;
      }
    </style>

  <% end %>

<div class="show-page">

<p>
  <strong>Name:</strong>
  <%= @library.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @library.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @library.country %>
</p>

<p>
  <strong>Url:</strong>
  <%= @library.url %>
</p>

<p>
  <strong>Image Url:</strong>
  <%= @library.pic_url %>
</p>

<%= link_to '| Edit', edit_library_path(@library) %> |
<%= link_to 'Back |', libraries_path %>
</div>

app/views/places_api/index.html.erb
<h1>PlacesApi#index</h1>
<p>Find me in app/views/places_api/index.html.erb</p>